-- AlterTable
ALTER TABLE "users" ADD COLUMN     "last_match_at" TIMESTAMPTZ(6),
ADD COLUMN     "rating" DOUBLE PRECISION NOT NULL DEFAULT 1500,
ADD COLUMN     "rating_deviation" DOUBLE PRECISION NOT NULL DEFAULT 350;
